adds rolling window support
scicloj/tablecloth.time pull request #15
Opened 2021-02-20 19:20 UTC by rsiddharthan

2021-02-28 04:15 UTC, rsiddharthan commented
Refactored code and switched to using updated slice function.

TODO #1. Switch to the new group-by that supports ordered datasets
TODO #2. Discuss if rolling-window can operate on index. It will require changed to slice to do the same

2021-03-03 04:06 UTC, rsiddharthan commented
Checked in version is an ordered dataset.

TODO: Add sample test cases for time based indices.

2021-03-06 02:30 UTC, rsiddharthan commented
Checked in support for column-name in function signatures. 
This allows both int based and time based indices to work

2021-03-09 02:03 UTC, ezmiller commented
@rsiddharthan the tests are failing, I think because midje needs to be included in the project dependencies in project.clj. The error:
>    Could not locate midje/sweet__init.class, midje/sweet.clj or midje/sweet.cljc
   on classpath.

2021-03-09 03:49 UTC, ezmiller commented
@rsiddharthan I added the midje dependency to project.clj, but I'm still getting an error:
```clj
 Syntax error compiling at (tablecloth/time/api/rolling_window_test.clj:7:1).
Unable to find column {{:loc 0}=[0], {:loc 1}=[0 1], {:loc 2}=[0 1 2], {:loc 3}=[1 2 3], {:loc 4}=[2 3 4], {:loc 5}=[3 4 5], {:loc 6}=[4 5 6], {:loc 7}=[5 6 7], {:loc 8}=[6 7 8], {:loc 9}=[7 8 9]}
```
Tried to understand it but nothing jumped out at me. Maybe it will be familiar to you.

2021-03-09 07:05 UTC, ezmiller commented
@rsiddharthan the command I ran to run your tests on your new test file on the command line was
```
lein midje tablecloth.time.api.rolling-window-test
```

2021-03-13 23:19 UTC, ezmiller requested changes
@rsiddharthan submitting my review now, now that we've go the tests worked out. I'll mark it "request changes" only because of the comment about the `import` statements that should be moved to the `ns` form.

2021-03-14 00:47 UTC, rsiddharthan commented on src/tablecloth/time/api/rolling_window.clj
> +  (:require [tablecloth.api :as tablecloth]
updated code to move the java imports

2021-03-14 00:47 UTC, rsiddharthan commented on src/tablecloth/time/api/rolling_window.clj
> +(import java.util.LinkedHashMap)
updated

2021-03-14 00:49 UTC, rsiddharthan commented on src/tablecloth/time/api/rolling_window.clj
> +(defn- instructions
renamed to rw-map. This remains a private function, as I prefer the single public rolling-window function

2021-03-14 04:00 UTC, ezmiller approved these changes
@rsiddharthan the changes look good. I will approve, but I think we want to get to the bottom of the odd diffs related to the slice tests and the change to support in slice, lest we end up messing up `main` somehow. 

Also looks like there is a merge conflict which is not surprising in the least, so we'll need to merge main into this branch before we can merge. Happy to help with that process if it's unfamiliar.

2021-03-19 19:47 UTC, merged